### ISSUE TITLE
Map refinements

### ISSUE THREAD

**Issue by chrzyki** [clld/numerals#12]
Will have to check how much app-specific modifications each of these requires, but the following map refinements might be nice to have:

- chop map on Greenland/Iceland rather than in the Pacific
- show missing languages (in grey) -> make map filtering possible (e.g. only language family X?)
- values on map (don't know how feasible this is)

**Comment by xrotwang** [comment]
Regarding pacific-centered maps: That's a simple setting in `appconf.ini`, e.g. https://github.com/clld/wals3/blob/c355723fe4b757fc90e297656e7adcd006a2465d/wals3/appconf.ini#L6

**Comment by chrzyki** [comment]
Ah, awesome, thanks!

**Comment by SimonGreenhill** [comment]
Implemented here: https://github.com/clld/numerals/blob/master/numerals/appconf.ini#L5
