### ISSUE TITLE
Missing data versus numeral does not exist

### ISSUE THREAD

**Issue by chrzyki** [clld/numerals#13]
We need to differentiate between data points that are missing versus lexical items that do not exist for a specific language. I suppose, however, that we can only get this partially (if at all) from Eugene's data.

**Comment by SimonGreenhill** [comment]
I think this is probably impossible, right? I wonder if there are forms marked as  "-" or "∅" or (I hope not) "Ø" (U+00D8 LATIN CAPITAL LETTER O WITH STROKE)
