### ISSUE TITLE
Language pages should have column order: parameter, value

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/numerals#18]
Column ordering is currently "value, parameter" which is slightly weird. Also good to have the comment/notes field here (#7)

**Comment by SimonGreenhill** [comment]
Thanks Christoph, does this catch 20, 30, 40, etc too?

**Comment by chrzyki** [comment]
Yes, I can re-deploy quickly so you can double check. Also prematurely closed this, sorry, still missing the comment field. Adding this right now.

**Comment by SimonGreenhill** [comment]
No worries about deploying, I believe you (just wondered if [0, 1] thing was special casing)!

**Comment by chrzyki** [comment]
https://numerals.clld.org/languages/aarihtm-1 Okay like this?

**Comment by SimonGreenhill** [comment]
and if you're on this, I also just opened https://github.com/clld/numerals/issues/26 which is related.

**Comment by SimonGreenhill** [comment]
Perfect! #26 can be closed now too (I guess the default sort is column number 1?)
