### ISSUE TITLE
URL for phylogenies should be ./phylogenies/

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/numerals#19]
It's currently ./phylogenys/ which is bad.

**Comment by SimonGreenhill** [comment]
this looks fixed.

**Comment by Bibiko** [comment]
It's possible to fix this. @xrotwang Are they any concerns?

**Comment by xrotwang** [comment]
Just the default concern: Any custom code, i.e. straying away from the defaults, should only be added if necessary. I'd leave it to @SimonGreenhill to decide here. Personally, I think I've seen (and created) worse URLs without getting many complaints :)

**Comment by SimonGreenhill** [comment]
I always check them -- URLS should be beautiful! :) can we please change it?
