### ISSUE TITLE
Value page needs concepticon definition of the numeral

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/numerals#22]
It's unclear what [these](https://numerals.clld.org/valuesets/abkhazhtm-1-14) pages refer to, so having the concepticon definition shown would help (c.f. #16)

**Comment by Bibiko** [comment]
are digits not enough? - Value Set Tawala, Papua New Guinea - 99

**Comment by SimonGreenhill** [comment]
yeah, it's clearer though?
