### ISSUE TITLE
Base calculation and other post-processing

### ISSUE THREAD

**Issue by chrzyki** [clld/numerals#28]
https://github.com/clld/numerals/commit/252019388aa0f4877bb64eff6fe4507b03714713 changes the DB creation script in that it now takes the Lexibank CLDF as a source. Here, for now, I've skipped the calculation of the base parameter because I wasn't sure where we'd like to do this:

- still in the DB creation script
- or in the respective Lexibank datasets (channumerals, etc.)

Opinions, @SimonGreenhill?

**Comment by SimonGreenhill** [comment]
Oh, this is a good question.  

I can see that it sits naturally in the DB creation stage, but we should probably publish this as well with the CLDF in a StructureDataset -- if only because otherwise we will have people asking us where to get these data from.  In which case maybe the lexibank-x.py code can do the heavy lifting for us?

Are we doing this on `channumerals` or the polished subset (`numerals`)?

**Comment by chrzyki** [comment]
Yes, my tendency is that this is a better fit for the datasets proper as well. I also see it as a candidate for all the datasets (e.g. `channumerals`, `numerals`, etc.) since it can be calculated automatically.

**Comment by xrotwang** [comment]
Hm. So this would be a candidate for some sort of library to enrich CLDF datasets? If we wanted to this in a totally generic way, it would operate on ordered counterparts for [concept sets](https://concepticon.clld.org/parameters) with ontological category *Number*, I guess.

**Comment by SimonGreenhill** [comment]
Yeah I think so. Be nice if it can 'hook' into lexibank's generator somehow? (cmd_enrich(cldf_dataset)?).

**Comment by xrotwang** [comment]
Yes, or maybe something like
```python
def iter_visitors(self):
    yield compute_numeral_base
```
in the dataset-specific code and
```python
    for visitor in self.iter_visitors:
        visitor(dataset)
```
in `pylexibank.dataset`.
```

**Comment by SimonGreenhill** [comment]
Ok, that looks good. In fact I think I like this a lot, as visitors can then be lightweight, decoupled, encapsulated and testable. e.g. things like lexibank's transcription/orthography checking, or readme generator would be tidier here than how it is at the moment which is a bit ugly. It'd also make it easy to extend lexibank's summaries etc by dropping in a new default visitor function in pylexibank.

I guess there's a question about whether visitor() works on rows of CLDF or all of CLDF (or both).  I could see wanting functions on rows (e.g. calculate wordlength or something), as well as dataset (e.g. calculate base, or number of phonemes, etc).

**Comment by xrotwang** [comment]
Yes, it's tidier. I can see this approach having limits, though, because iterating over rows in CLDF is slow. So maybe we need something like a registry for callbacks, i.e. a dataset can register - e.g. - a per `LanguageTable` row callback, or a callback for a "post-creation" hook of the whole dataset. This could still become messy, when callbacks have to be called in particular order, or need coordinated data, but I guess it would be worth a try.

**Comment by SimonGreenhill** [comment]
yeah, CLDF write is a rare operation though, so slow isn't necessarily too painful. However it might be nice to get some benchmarks/profiles on how long an iterate takes to see how painful. The [csvw](https://github.com/cldf/csvw/blob/master/src/csvw/metadata.py#L632) code here  --  (this is how pycldf iterates right?) -- looks rather complex, so might be optimisable?

**Comment by Bibiko** [comment]
I added to cldf languages.csv a column called 'Base' which contains the info found in the comments if the contributor stated the used system clearly, eg: XYZ has a ... system - this info could be checked in cldf languages.csv since in the comments one can find lots of useful informations.

**Comment by chrzyki** [comment]
Is base always a language-wide property or could it also be a counting system-wide property?

**Comment by Bibiko** [comment]
So far it is a language-variant-wide property. It could be that a language has more than one counting system. The info is parsed against the comments. One should discuss how to store this information, eg as digits (10) or names (decimal).

**Comment by SimonGreenhill** [comment]
Ok, so this is no longer relevant, right? Please reopen if it is.
