### ISSUE TITLE
Link to Swadesh/Concepticon concepts

### ISSUE THREAD

**Issue by chrzyki** [clld/numerals#4]
Filter lists on the basis of Swadesh concepts/link values to Concepticon concepts.

**Comment by chrzyki** [comment]
Huh, cool, I was never thinking of the reverse (only of linking the numbers that are in Concepticon from Numerals) but yeah, I agree! I can easily create a list of these candidates.

**Comment by xrotwang** [comment]
This PR shouldn't be too large - as far as I remember the numerals data. Once numeralbank is public, it could serve as the publication from which the concepticon concept list for it is derived.

**Comment by chrzyki** [comment]
This is done for the most frequent numerals and will be done in chunks after an initial release.
