### ISSUE TITLE
Harvest numbers from lexibank/clics?

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/numerals#54]
It occurs to me that we have a lot of number data in lexibank (or at least the published CLICS datasets). Does it make sense to write a harvester for these to extract the lexemes for numbers from them and add these as contributions to numeral bank?

**Comment by xrotwang** [comment]
Hm. I don't think it would be very useful for users of the numeralbank data. But such a comparison could certainly go into a "Technical Validation" section of a paper describing numeralbank :)

**Comment by Bibiko** [comment]
I agree with @xrotwang - I see Numeralbank as deliver for Lexikank, not the other way around. But I also find it interesting to compare the Numeralbank data with the other Lexibank data sets. Maybe a small app would be helpful, which allows to aggregate a subset of parameters from all Lexibank datasets (if such a thing does not exist yet)

**Comment by chrzyki** [comment]
Closing in favour of issue in `pynumerals`.
