### ISSUE TITLE
numerals.clld.org -> numeralbank.clld.org

### ISSUE THREAD

**Issue by chrzyki** [clld/numerals#79]
I can't quite remember how the URL `numerals.clld.org` came into being. Wouldn't it be better, for consistency with the other projects/apps, to have `numeralbank.clld.org`?

**Comment by xrotwang** [comment]
The argument from consistency could also be made **for** `numerals.clld.org`: The name of the domain is by default derived from the name of the clld web app package ...

By the same token, it could be argued that there is no consistency here. So, in the absence of other arguments I'd leave things as they are :)

**Comment by chrzyki** [comment]
Sorry, I didn't express myself well: I think for the sake of consistency the app should be `numeralbank` as well, no? I.e. every instance of `numerals` -> `numeralbank`?

**Comment by chrzyki** [comment]
Sounds reasonable, thanks!
